# Generated by Django 3.0.4 on 2020-03-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
